#{ id => 321934,
   resource_state => detailed,
   external_id => <<"2012-12-12_21-40-32-80-29011.fit">>,
   upload_id => 361720,
   athlete => #{ id => 227615,
                 resource_state => meta },
   name => <<"12/12/2012 San Francisco">>,
   description => <<"the best ride ever">>,
   distance => 4475.4,
   moving_time => 1303,
   elapsed_time => 1333,
   total_elevation_gain => 8.6,
   type => run,
   start_date => {{2012,12,13}, {03,43,19}},
   start_date_local => {{2012,12,12}, {19,43,19}},
   timezone => <<"(GMT-08:00) America/Los_Angeles">>,
   start_latlng => {37.8, -122.27},
   end_latlng => {37.8, -122.27},
   location_city => <<"San Francisco">>,
   location_state => <<"CA">>,
   location_country => <<"United States">>,
   achievement_count => 6,
   kudos_count => 1,
   comment_count => 1,
   athlete_count => 1,
   photo_count => 0,
   total_photo_count => 0,
   photos => #{ count => 2,
                primary => #{ source => strava,
                              unique_id => <<"d64643ec9205">>,
                              urls => #{ 100 => <<"http://pics.com/28b9d28f-128x71.jpg">>,
                                         600 => <<"http://pics.com/28b9d28f-768x431.jpg">> } } },
   map => #{ id => <<"a32193479">>,
             polyline => <<"kiteFpCBCD]">>,
             summary_polyline => <<"{cteFjcaBkCx@gEz@">>,
             resource_state => detailed },
   trainer => false,
   commute => false,
   manual => false,
   private => false,
   flagged => false,
   workout_type => long_run,
   gear => #{ id => <<"g138727">>,
              primary => true,
              name => <<"Nike Air">>,
              distance => 88983.1,
              resource_state => summary },
   average_speed => 3.4,
   max_speed => 4.514,
   calories => 390.5,
   has_kudoed => false,
   segment_efforts => [ #{ id => 543755075,
                           resource_state => summary,
                           name => <<"Dash for the Ferry">>,
                           segment => #{ id => 2417854,
                                         resource_state => summary,
                                         name => <<"Dash for the Ferry">>,
                                         activity_type => run,
                                         distance => 1055.11,
                                         average_grade => -0.1,
                                         maximum_grade => 2.7,
                                         elevation_high => 4.7,
                                         elevation_low => 2.7,
                                         start_latlng => {37.7905785, -122.27015622},
                                         end_latlng => {37.79536649, -122.2796434},
                                         climb_category => undefined,
                                         city => <<"Oakland">>,
                                         state => <<"CA">>,
                                         country => <<"United States">>,
                                         private => false },
                           activity => #{ id => 32193479,
                                          resource_state => meta },
                           athlete => #{ id => 3776,
                                         resource_state => meta },
                           kom_rank => 2,
                           pr_rank => 1,
                           elapsed_time => 304,
                           moving_time => 304,
                           start_date => {{2012,12,13}, {03,48,14}},
                           start_date_local => {{2012,12,12}, {19,48,14}},
                           distance => 1052.33,
                           start_index => 5348,
                           end_index => 6485,
                           hidden => false,
                           achievements => [ #{ type_id => 2,
                                                type => overall,
                                                rank => 2 },
                                             #{ type_id => 3,
                                                type => pr,
                                                rank => 1 } ] } ],
   splits_metric => [ #{ distance => 1002.5,
                         elapsed_time => 276,
                         elevation_difference => 0,
                         moving_time => 276,
                         split => 1 },
                      #{ distance => 475.7,
                         elapsed_time => 139,
                         elevation_difference => 0,
                         moving_time => 139,
                         split => 5 } ],
   splits_standard => [ #{ distance => 1255.9,
                           elapsed_time => 382,
                           elevation_difference => 3.2,
                           moving_time => 382,
                           split => 3 } ],
   best_efforts => [ #{ id => 273063933,
                        resource_state => summary,
                        name => <<"400m">>,
                        activity => #{ id => 32193479 },
                        athlete => #{ id => 3776 },
                        elapsed_time => 105,
                        moving_time => 106,
                        start_date => {{2012,12,13}, {03,43,19}},
                        start_date_local => {{2012,12,12}, {19,43,19}},
                        distance => 400,
                        achievements => [] },
                     #{ id => 273063935,
                        resource_state => summary,
                        name => <<"1/2 mile">>,
                        activity => #{ id => 32193479 },
                        athlete => #{ id => 3776 },
                        elapsed_time => 219,
                        moving_time => 220,
                        start_date => {{2012,12,13}, {03,43,19}},
                        start_date_local => {{2012,12,12}, {19,43,19}},
                        distance => 805,
                        achievements => [] } ] }.
