#{ id => 1234567,
   resource_state => summary,
   title => <<"Test Group Event">>,
   description => <<"Very fun group ride">>,
   club_id => 1,
   organizing_athlete => #{ id => 227615,
                            resource_state => summary,
                            firstname => <<"John">>,
                            lastname => <<"Applestrava">>,
                            profile_medium => <<"http://pics.com/227615/medium.jpg">>,
                            profile => <<"http://pics.com/227615/large.jpg">>,
                            city => <<"San Francisco">>,
                            state => <<"California">>,
                            country => <<"United States">>,
                            sex => male,
                            friend => accepted,
                            follower => accepted,
                            premium => true,
                            created_at => {{2009,08,26}, {13,42,05}},
                            updated_at => {{2013,01,11}, {18,51,00}} },
   activity_type => ride,
   created_at => {{2009,08,26}, {13,42,05}},
   route_id => 123456,
   women_only => false,
   private => true,
   skill_levels => 1,
   terrain => 0,
   upcoming_occurrences => [ {{2015,04,19}, {18,47,59}},
                             {{2015,04,20}, {18,47,59}},
                             {{2015,04,21}, {18,47,59}},
                             {{2015,04,22}, {18,47,59}},
                             {{2015,04,23}, {18,47,59}} ],
   address => <<"1 Happening St. Reno, NV">> }.
